import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { ReactNode } from 'react';

import './globals.css'
import { Navbar } from "../components/ui/navbar";

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (

    
    <ClerkProvider>
      <html lang="en">
        <body className={`antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16 sticky top-0 ">
            <Navbar />
            
          </header>
          
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}